name: Generate ASCII
on: push
jobs:
    ascii:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: Bootstrap the node
              run: |
               sudo apt-get install -y cowsay
               sudo -i
            - name: generate ascii
              run: cowsay -f dragon "run for cover, I am a Dragon..RAWR" >> dragon.txt
            - name: test the file
              run: grep -i "dragon" dragon.txt
            - name: read the file
              run: cat dragon.txt
            - name: where are you
              run: pwd && ls
            - name: what are your specifications
              run: df -hT
            - name: compose a file
              run: echo "composing a file" | tee -a test.out
            - name: view the contents of the file
              run: cat test.out
            - name: read a file from the repo
              run: cat README.md
            - name: checkout local contents again
              run: pwd && ls
