name: rkulkarni-test
on: push
jobs:
    rkulkarni-test:
        runs-on: ubuntu-latest
        steps:
            - name: test
              run: whoami
            - name: checkout
              uses: actions/checkout@v4
            - name: list files
              run: ls -lrta && pwd
            - name: execute shell script
              run: ./.github/workflows/ascii-script.sh