name: rkulkarni-test
on: push
jobs:
    rkulkarni-test:
        runs-on: ubuntu-latest
        steps:
            - name: test
              run: whoami
            - name: checkout
              uses: actions/checkout@v4
            - name: list files
              run: ls -lrta && pwd && chmod +x ./.github/workflows/ascii-script.sh
            - name: execute shell script
              run: ./.github/workflows/ascii-script.sh
    rkulkarni-test-1:
        needs: rkulkarni-test
        runs-on: ubuntu-latest
        steps:
            
            - name: test
              run: echo "hi" > test.out
            - name: upload
              uses: actions/upload-artifact@v4
              with:
                name: my-artifact
                path: test.out
            - name: list files
              run: ls -lrta && pwd
    rkulkarni-test-2:
        needs: rkulkarni-test-1
        runs-on: ubuntu-latest
        steps:
            - name: test
              run: whoami
            - name: checkout
              uses: actions/download-artifact@v4
              with:
                name: my-artifact
            - name: list files
              run: ls -lrta && pwd